### PR TITLE
Allow sorting of each_with collections

### PR DESCRIPTION
**Pull request by yitznewton**

### CODE REVIEW

**Comment by robincurry** [comment]
Good stuff, @yitznewton. This will come in handy elsewhere I bet. I'm :+1:  when :green_apple:

**Comment by natemcdowel** [comment]
:+1:

**Comment by yitznewton** [comment]
Looks like you need to be the merger here, @robincurry

**Comment by yitznewton** [comment]
But I don't see any Travis build status

**Comment by yitznewton** [comment]
@robincurry looks like an errored run; can you restart travis?

**Comment by robincurry** [comment]
Keeps failing on the Ruby 2.1.5 build. Not sure why

**Comment by yitznewton** [comment]
I just rebased onto robincurry/master; let's see if that works.

**Comment by robincurry** [comment]
Checked locally as well. I think it is an issue with travis / bundler. Will research outside of this PR.

**Pull request merged**
