### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by yitznewton**

### CODE REVIEW

**Comment by yitznewton** [comment]
https://travis-ci.org/yitznewton/shape/builds/55641476

**Comment by yitznewton** [comment]
https://travis-ci.org/yitznewton/shape/builds/55641917

**Comment by yitznewton** [comment]
Running into problems with Ruby 1.9. If you want to go forward with Travis, perhaps we just remove 1.9 from the build.

**Comment by robincurry** [comment]
I'm comfortable with that. 1.9.3 was End-of-Lifed in February I believe.

**Comment by yitznewton** [comment]
https://travis-ci.org/yitznewton/shape/builds/55648834

**Comment by yitznewton** [comment]
That passed

**Comment by robincurry** [comment]
:tada:

**Pull request merged**
